### PR TITLE
NEW: Environment type check.

### PR DESCRIPTION
**Pull request by frankmullenger**
Adding an environment check, useful for confirming environment settings have not changed on live environments.

### CODE REVIEW

**Comment by frankmullenger** [comment]
Failing checks all seem related to missing GridFieldArchiveAction, resolving that issue seems beyond the scope of the changes in this pull request?

**Comment by ScopeyNZ** [comment]
> Failing checks all seem related to missing GridFieldArchiveAction, resolving that issue seems beyond the scope of the changes in this pull request?

Yep. It'll need a travis configuration update. I'll sort that for you

**Comment by frankmullenger** [comment]
Great, thanks @ScopeyNZ! Does Travis need to use 5.6 as well? https://github.com/silverstripe/silverstripe-environmentcheck/blob/master/.travis.yml#L9

**Comment by NightJar** [comment]
@frankmullenger 	yep, until SS5.

**Comment by ScopeyNZ** [comment]
> > Does Travis need to use 5.6 as well? [/.travis.yml@`master`#L9](https://github.com/silverstripe/silverstripe-environmentcheck/blob/master/.travis.yml#L9)
> 
> @frankmullenger yep, until SS5 (and this module is duly updated to be compatible with such).

Actually SilverStripe has committed to dropping support for PHP 5.x in June. So whatever release of SilverStripe that comes after that date will not need to support PHP 5.x. See the announcement here for more details: https://www.silverstripe.org/blog/our-plan-for-ending-php-5-6-support-in-silverstripe-4/

**Comment by ScopeyNZ** [comment]
I've changed the base branch to `master` for this enhancement. Travis configuration is also fixed I just need to close/re-open to get the tests running with the new config.

**Comment by NightJar** [comment]
@ScopeyNZ my understanding is that SilverStripe will drop _active_ support for PHP 5.6 in June - this is to say that testing/building on that version will stop. Modules (and core) are _not_ expected to break until 5.5 - but support levels will be ... reduced.

This is to say that Travis should still remain green - backwards compatibility is to be maintained.

**Comment by frankmullenger** [comment]
Thanks @ScopeyNZ, looks like Scrutinizer failed on analysing silverstripe/framwork. Presume the codecov/patch failure is acceptable as these additional checks are generally added without unit tests?

**Comment by NightJar** [comment]
@frankmullenger it is probably that the srcutinizer config needs updating - I had this issue recently on another module (comments). It was using an outdated composer version, and @robbieaverill fixed it for me [like this](https://github.com/silverstripe/silverstripe-comments/pull/277/files#diff-9cbd60c9b1418df594663892b0b740a7)

Not sure about the specifics, but hopefully this example might help :)

**Comment by ScopeyNZ** [comment]
I don't really know what I'm doing tbh but I pushed a commit that updates the scrutinizer config.

**Comment by frankmullenger** [comment]
Nice one, thanks!

**Comment by NightJar** [comment]
Well whatever you did it seems to have worked @ScopeyNZ xD

**Pull request merged**
